### PR TITLE
Update to NatCam 2.1

### PR DESCRIPTION
**Pull request by olokobayusuf**
This update comes with structural changes to the example project itself. In a nutshell:
- All camera handling has been abstracted away to implementations of `ICameraSource`. Implementations of this interface allow for starting the camera at a specified resolution and framerate, starting the preview (and invoking client-provided callbacks corresponding to new frames), switching cameras, and accessing the preview data as either a `Mat` or `Color32[]`.
- Similarly, all the examples have been made to inherit `ExampleBase`, which provides common functionality for applying different image processing on the camera preview and other minor things
- All orientation handling is done by the camera source, instead of the example script. As a result, the `Mat` or `Color32[]` provided by a camera source is always upright.
- NatCam requires Unity 5.3 at least, which coincidentally is where `UnityEngine.SceneManagement` is introduced. So all references to `Application.LoadLevel` have been removed.

With all these changes, the code is hopefully easier to parse, understand, and reuse.

### CODE REVIEW

**Comment by EnoxSoftware** [comment]
Thank you for the pull request.
I tried new version NatCam (2.1f3) and got an error when device orientation has changed.
This error will be fixed soon?

natcam_orientation_error

**Comment by olokobayusuf** [comment]
Hm that's curious. What device did you test on? Can you attach the logs from logcat in a txt file?

**Comment by EnoxSoftware** [comment]
NatCam 2.1f3, Unity 5.6f2, IL2CPP
Pixel (G-2PW4100), Android9

The test device is Pixel.
I have not tried it with other devices yet.

In addition to the above errors, sometimes the application crashed.
I attached the logs of GrayCam and MiniCam example.
[NatCam_GreyCam_orientation_error_log.txt](https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/files/2733940/NatCam_GreyCam_orientation_error_log.txt)
[NatCam_MiniCam_orientation_error_log.txt](https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/files/2733942/NatCam_MiniCam_orientation_error_log.txt)
[NatCam_MiniCam_orientation_crash_log.txt](https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/files/2733943/NatCam_MiniCam_orientation_crash_log.txt)

**Comment by EnoxSoftware** [comment]
===================================
Test Environment: NatCam 2.1f3, Unity 5.6f2, IL2CPP
Test Device: Nexus7 , Android6.0.1

- When the orientation of the device changed, the preview image was destroyed.
- Sometimes the application crashed.

[NatCam_Nexus7_MiniCam_crash_log.txt](https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/files/2736486/NatCam_Nexus7_MiniCam_crash_log.txt)

===================================
Test Environment: NatCam 2.1f3, Unity 5.6f2, IL2CPP
Test Device: Zenfone2 , Android6.0.1

- Preview image flickering has always occurred.
- When the orientation of the device changed, the preview image was destroyed.

[NatCam_Zenfone2_MiniCam_orientation_error_log.txt](https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/files/2736433/NatCam_Zenfone2_MiniCam_orientation_error_log.txt)
[NatCam_Zenfone2_MiniCam_orientation_error.mp4.zip](https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/files/2736442/NatCam_Zenfone2_MiniCam_orientation_error.mp4.zip)

- Sometimes the application crashed.

===================================

**Comment by olokobayusuf** [comment]
Thanks for these logs, and thanks for merging. I'm working on the fix for the flickering and crashing.

**Pull request merged**
